name: flip_clock
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wakelock: ^0.6.2
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0
flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        # https://fonts.google.com/specimen/Roboto+Mono?classification=Monospace
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
